# Generated by Django 2.2 on 2021-11-04 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_imie', models.CharField(max_length=30)),
                ('autor_nazwisko', models.CharField(max_length=30)),
                ('data_dodania', models.DateField(default=datetime.datetime(2021, 11, 4, 8, 0, 47, 172176, tzinfo=utc))),
                ('tresc', models.TextField()),
            ],
        ),
    ]
