# Generated by Django 2.2 on 2021-11-04 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 8, 14, 47, 254768, tzinfo=utc)),
        ),
    ]
